# s = PivotTreeArray(5)
# for i in range(31):
#     s.insert(i)
# s.insert(5)
# print(len(s))
# print(s._PivotTreeArray__data)

# s.remove(5)
# print(len(s))
# print(6 in s)
# print(s._PivotTreeArray__data)
# print(s[6])
# print(s.lower_bound(-1))
# print(s.upper_bound(5))
# print(s.upper_bound(6))
