import cgitb

import wsgiref.headers
import wsgiref.handlers
import wsgiref.validate
import wsgiref.simple_server
import wsgiref.util
import wsgiref.simple_server
import wsgiref
import urllib
import urllib.request
import urllib.parse
import urllib.error
import urllib.robotparser
import http
import http.client
import ftplib
import poplib
import imaplib
import nntplib
import smtplib
import smtpd
import telnetlib
import uuid
import socketserver
import http.server
import http.cookies
import http.cookiejar
import xmlrpc
import xmlrpc.client
import xmlrpc.server
import ipaddress
import audioop
import aifc
import sunau
import wave
import chunk
import colorsys
import imghdr
import sndhdr
import ossaudiodev
import gettext
import locale
import turtle
import cmd
import shlex
import tkinter
import tkinter.colorchooser
import tkinter.font
import tkinter.simpledialog
import tkinter.filedialog
import tkinter.commondialog
import tkinter.messagebox
import tkinter.scrolledtext
import tkinter.dnd
import tkinter.ttk
import tkinter.tix
import typing
import pydoc
import doctest
import unittest
import unittest.mock
import test
import test.support.script_helper
import test.support.socket_helper
import test.support.warnings_helper
import test.support.bytecode_helper
import bdb
import faulthandler
import pdb
import timeit
import trace
import tracemalloc
import distutils
import venv
import zipapp
import sys
import sysconfig
import builtins
import warnings
import dataclasses
import contextlib
import abc
import atexit
import traceback
import __future__
import gc
import inspect
import site
import code
import codeop
import zipimport
import pkgutil
import modulefinder
import runpy
import importlib
import importlib.abc
import importlib.resources
import importlib.machinery
import importlib.util
import importlib.metadata
import ast
import symtable
import token
import keyword
import tokenize
import tabnanny
import pyclbr
import py_compile
import compileall
import dis
import pickletools
# import msilib
# import msvcrt
# import winreg
# import winsound
import posix
import pwd
import spwd
import grp
import crypt
import termios
import tty
import pty
import fcntl
import pipes
import resource
import nis
import syslog
import optparse
# import imp
import cgi
import webbrowser
import xml
import xml.parsers.expat
import xml.sax.saxutils
import xml.sax.handler
import xml.sax
import xml.dom.pulldom
import xml.dom.minidom
import xml.dom
import xml.etree
import html.entities
import html.parser
import html
import uu
import quopri
import binascii
# import binhex
import base64
import mimetypes
import mailbox
import mailcap
import json
import email
import email.iterators
import email.utils
import email.encoders
import email.charset
import email.header
import email.mime
import email.message
import email.contentmanager
import email.headerregistry
import email.errors
import email.policy
import email.generator
import email.parser
import email.message
import mmap
import signal
import asynchat
import asyncore
import selectors
import asyncio
import select
import ssl
import socket
import _thread
import contextvars
import queue
import sched
import subprocess
import concurrent.futures
import concurrent
import multiprocessing
import multiprocessing.shared_memory
import multiprocessing.dummy
import multiprocessing.sharedctypes
import threading
import ctypes
import errno
import platform
import curses.panel
import curses.ascii
import curses
import getpass
import logging
import logging.handlers
import logging.config
import getopt
import argparse
import time
import io
import os
import secrets
import hmac
import hashlib
import plistlib
import xdrlib
import netrc
import configparser
import csv
import tarfile
import zipfile
import lzma
import bz2
import gzip
import zlib
import sqlite3
import dbm
import marshal
import shelve
import copyreg
import pickle
import shutil
import linecache
import fnmatch
import glob
import tempfile
import filecmp
import stat
import fileinput
import os.path
import pathlib
import operator
import functools
import itertools
import statistics
import random
import fractions
import decimal
import cmath
import math
import numbers
import graphlib
import enum
import reprlib
import pprint
import types
import copy
import weakref
import array
import bisect
import heapq
import collections.abc
import collections
import calendar
import zoneinfo
import datetime
import codecs
import struct
import rlcompleter
import readline
import stringprep
import unicodedata
import textwrap
import difflib
import re
import string


if __name__ == '__main__':
    ...
