version: '3.9'

services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - python.env
    image: kagemeka/$PROJECT:latest
    restart: on-failure
    tty: true
    volumes:
      - type: bind
        source: $ROOT
        target: /root/$PROJECT
        volume:
          nocopy: true
        read_only: false
    working_dir: /root/$PROJECT
